name = "httpclient"
description = "HTTP/HTTPS client library"
version = "1.0.0"
licenses = "MIT"
website = "https://github.com/bracke/httpclient"
authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]

tags = ["http", "https", "client", "tls", "http2", "cache", "async"]

[[depends-on]]
gnat_native = "=15.2.1"

[[depends-on]]
zlib = "*"

[[pins]]
zlib = { path='../zlib' }

[[actions]]
type = "test"
command = ["sh", "-c", "cd tests && alr build && ./bin/tests"]
