with Ada.Containers.Vectors;
with Ada.Strings.Unbounded;

with Http_Client.Errors;
with Http_Client.Request_Bodies;
with Http_Client.Requests;

package Http_Client.Multipart is
   --  Release surface: stable public API for 1.0.0.
   --  Source compatibility for documented public declarations in this
   --  package is covered by docs/compatibility.md unless a declaration
   --  is explicitly marked experimental or implementation-only below.
   --  Ada-native multipart/form-data request-body helpers.
   --
   --  This package builds multipart/form-data bodies on top of the request-body
   --  producer model. It generates only multipart framing and part headers; it
   --  performs no browser form parsing, HTML automation,
   --  MIME type inference, async upload scheduling, HTTP caching, response
   --  parsing, authentication, redirects, retries, proxying, or TLS work.
   --
   --  Multipart forms are not task-safe. A form object owns its streaming
   --  cursor while a request body produced from it is being sent.

   Max_Boundary_Length : constant Natural := 70;
   Max_Field_Name_Length : constant Natural := 128;
   Max_File_Name_Length : constant Natural := 255;
   Max_Content_Type_Length : constant Natural := 128;
   Max_Part_Header_Length : constant Natural := 4096;
   Max_Part_Count : constant Natural := 1024;

   type Multipart_Form is limited private;
   --  Mutable multipart/form-data builder and streaming producer.
   --
   --  Text and binary memory parts are replayable. File-backed parts are
   --  replayable when the referenced file can still be opened and still has
   --  the captured size when the body is read. Unknown-length parts are not
   --  supported in this release.

   function Create return Multipart_Form;
   --  GNATdoc contract.
   --  @return Subprogram result.
   --  Return an empty form with a generated ASCII-safe boundary.
   --
   --  Prefer this constructor for ordinary use. Default-initialized form
   --  objects also start with a fixed valid boundary so operations never emit
   --  an empty boundary.
   --
   --  Generated boundaries are syntactically valid and deliberately long enough
   --  for ordinary use. Memory parts are checked conservatively for active
   --  boundary-marker collisions when they are added and when a deterministic
   --  boundary is installed. This package does not scan arbitrary file-backed
   --  content for delimiter collisions; callers that require byte-for-byte
   --  deterministic fixtures may set and test an explicit boundary.

   procedure Clear (Form : in out Multipart_Form);
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  Remove all parts and reset the streaming cursor.

   function Is_Valid_Boundary (Boundary : String) return Boolean;
   --  GNATdoc contract.
   --  @param Boundary Subprogram parameter.
   --  @return Subprogram result.
   --  Return True for a conservative boundary value usable without quoting.

   function Set_Boundary
     (Form     : in out Multipart_Form;
      Boundary : String) return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Boundary Subprogram parameter.
   --  @return Subprogram result.
   --  Replace the form boundary for deterministic tests.
   --
   --  Boundaries must be non-empty, at most Max_Boundary_Length bytes, ASCII,
   --  and composed only of letters, digits, hyphen, underscore, and period.
   --  The boundary value is used exactly in delimiter lines and in the outer
   --  Content-Type generated by Content_Type and Attach.

   function Boundary (Form : Multipart_Form) return String;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @return Subprogram result.
   --  Return the active boundary.

   function Content_Type (Form : Multipart_Form) return String;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @return Subprogram result.
   --  Return the exact outer Content-Type value including boundary parameter.

   function Add_Field
     (Form  : in out Multipart_Form;
      Name  : String;
      Value : String) return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Name Subprogram parameter.
   --  @param Value Subprogram parameter.
   --  @return Subprogram result.
   --  Append a text field with preserved byte content.
   --
   --  The field name is emitted as a quoted Content-Disposition name
   --  parameter and is therefore validated against the ASCII-safe
   --  parameter policy. The value is rejected if it contains the active
   --  boundary marker sequence.

   function Add_Binary_Part
     (Form         : in out Multipart_Form;
      Name         : String;
      Data         : String;
      Filename     : String := "";
      Content_Type : String := "") return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Name Subprogram parameter.
   --  @param Data Subprogram parameter.
   --  @param Filename Subprogram parameter.
   --  @param Content_Type Subprogram parameter.
   --  @return Subprogram result.
   --  Append an in-memory binary part.
   --
   --  Data is preserved exactly, including CR, LF, NUL, and bytes that look
   --  like headers. Filename and Content_Type are optional and are validated
   --  when supplied. No MIME type is inferred. In-memory data is rejected if it
   --  contains the active boundary marker sequence.

   function Add_File
     (Form         : in out Multipart_Form;
      Name         : String;
      Path         : String;
      Filename     : String := "";
      Content_Type : String := "") return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Name Subprogram parameter.
   --  @param Path Subprogram parameter.
   --  @param Filename Subprogram parameter.
   --  @param Content_Type Subprogram parameter.
   --  @return Subprogram result.
   --  Append a file-backed part.
   --
   --  Path must name an ordinary file at construction time. The file size is
   --  captured for exact Content-Length computation and checked again during
   --  streaming. Directories, recursive traversal, symlink policy, archive path
   --  inference, and broad MIME inference are deliberately outside this API.

   function Part_Count (Form : Multipart_Form) return Natural;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @return Subprogram result.
   --  Return the number of appended parts.

   function Set_Max_Encoded_Length
     (Form       : in out Multipart_Form;
      Max_Length : Natural) return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Max_Length Subprogram parameter.
   --  @return Subprogram result.
   --  Set a form-local maximum encoded body length.
   --
   --  The limit is checked by Content_Length, To_Request_Body, and Attach. It
   --  includes all generated delimiter/header/CRLF bytes and all part content
   --  bytes. The default limit is Natural'Last. Exceeding the configured limit
   --  returns Multipart_Too_Large.

   function Is_Replayable (Form : Multipart_Form) return Boolean;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @return Subprogram result.
   --  Return True when the form can currently be replayed.
   --
   --  Memory-only forms are replayable. File-backed forms are replayable only
   --  while each captured file still exists as an ordinary file and still has
   --  the captured size. This is an advisory check; read failures can still be
   --  reported by the producer if the filesystem changes during upload.

   function Content_Length
     (Form   : Multipart_Form;
      Length : out Natural) return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Length Subprogram parameter.
   --  @return Subprogram result.
   --  Compute the exact encoded body length.
   --
   --  This release supports known-length forms only. The value includes delimiter
   --  lines, generated part headers, CRLF framing, part bytes, and the final
   --  closing delimiter with trailing CRLF. Empty forms are allowed and encode
   --  as just the final closing delimiter.

   function Render_Body
     (Form   : Multipart_Form;
      Output : out Ada.Strings.Unbounded.Unbounded_String)
      return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Output Subprogram parameter.
   --  @return Subprogram result.
   --  Render the complete body into memory for deterministic small tests.
   --
   --  Large file uploads should use To_Request_Body instead.

   function To_Request_Body
     (Form : aliased in out Multipart_Form)
      return Http_Client.Request_Bodies.Request_Body;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @return Subprogram result.
   --  Return a fixed-length replayable streaming request body backed by Form.
   --
   --  The caller must keep Form alive and must not mutate it while the request
   --  body is being executed. File-backed reads re-check the captured size; a
   --  changed or unreadable file causes deterministic producer failure rather
   --  than silently changing the encoded body. This convenience function returns
   --  Empty if length computation fails; use the status-returning overload
   --  when construction failure must be observed.

   function To_Request_Body
     (Form : aliased in out Multipart_Form;
      Body_Data : out Http_Client.Request_Bodies.Request_Body)
      return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Body_Data Subprogram parameter.
   --  @return Subprogram result.
   --  Build a fixed-length replayable streaming request body backed by Form.
   --
   --  This checked overload computes the encoded Content-Length first and
   --  returns Multipart_Too_Large if the generated framing and part lengths do
   --  not fit in Natural. On failure Body_Data is set to an empty body.

   function Attach
     (Form                 : aliased in out Multipart_Form;
      Request              : Http_Client.Requests.Request;
      Result               : out Http_Client.Requests.Request;
      Replace_Content_Type : Boolean := False)
      return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Subprogram parameter.
   --  @param Request Subprogram parameter.
   --  @param Result Subprogram parameter.
   --  @param Replace_Content_Type Subprogram parameter.
   --  @return Subprogram result.
   --  Rebuild Request with this multipart body and the matching outer
   --  Content-Type header.
   --
   --  If Request already has Content-Type and Replace_Content_Type is False,
   --  Invalid_Header is returned. Stale outer Content-Length and
   --  Transfer-Encoding fields are removed so the HTTP/1.1 serializer can add
   --  the exact fixed Content-Length for the multipart body. Part-level headers
   --  remain inside the body; no cookies, authorization, proxy, accept, or
   --  user-agent fields are added.

private
   use Ada.Strings.Unbounded;

   type Part_Kind is (Memory_Part, File_Part);

   type Multipart_Part is record
      Kind             : Part_Kind := Memory_Part;
      Name             : Unbounded_String := Null_Unbounded_String;
      Has_Filename     : Boolean := False;
      Filename         : Unbounded_String := Null_Unbounded_String;
      Has_Content_Type : Boolean := False;
      Part_Type        : Unbounded_String := Null_Unbounded_String;
      Data             : Unbounded_String := Null_Unbounded_String;
      Path             : Unbounded_String := Null_Unbounded_String;
      Length           : Natural := 0;
   end record;

   package Part_Vectors is new Ada.Containers.Vectors
     (Index_Type   => Positive,
      Element_Type => Multipart_Part);

   type Stream_Stage is
     (At_Part_Prefix,
      At_Part_Data,
      At_Part_Trailing_CRLF,
      At_Final_Boundary,
      At_Done);

   type Multipart_Form is new Http_Client.Request_Bodies.Body_Producer with record
      Boundary_Text : Unbounded_String :=
        To_Unbounded_String ("AdaHttpClientMultipartBoundaryDefault");
      Max_Length    : Natural := Natural'Last;
      Parts         : Part_Vectors.Vector;
      Read_Part     : Natural := 1;
      Stage         : Stream_Stage := At_Part_Prefix;
      Fragment      : Unbounded_String := Null_Unbounded_String;
      Fragment_Pos  : Natural := 1;
      Data_Pos      : Natural := 1;
   end record;

   overriding function Read_Some
     (Form   : in out Multipart_Form;
      Buffer : out String;
      Count  : out Natural) return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Multipart body producer state.
   --  @param Buffer Output buffer receiving encoded multipart bytes.
   --  @param Count Number of characters written to Buffer.
   --  @return Ok, End_Of_Stream, or a deterministic failure status.

   overriding function Reset
     (Form : in out Multipart_Form) return Http_Client.Errors.Result_Status;
   --  GNATdoc contract.
   --  @param Form Multipart body producer state to rewind.
   --  @return Ok when the form stream is reset.
end Http_Client.Multipart;
